### ISSUE TITLE
Allowing unsafe things...

### ISSUE THREAD

**Issue by felixangell** [ark-lang/rfcs#14]
Since one of the main goals isn't security (to the extent of Rust), perhaps we shouldn't bother with an `unsafe` block equivalent, and just allow unsafe code? We introduce something like `Box<T>` for safe memory, but still allow raw pointers, dereferencing, etc.

Perhaps instead of throwing an error, it could just produce a warning which can be disabled with an attribute, and maybe a flag for people who know what they're doing, i.e. kernel developers who need to mess around with memory addresses and what not.

:+1:

**Comment by MovingtoMars** [comment]
I think allowing unsafe code arbitarily could mean users could accidentally subvert the ownership/lifetimes system, creating a confusing runtime problem.

**Comment by felixangell** [comment]
@MovingtoMars Yeah, that's something that is possible; so we could still produce warnings for the unsafe things, but still allow it to compile?

**Comment by jack-cogan** [comment]
this sounds really cool because if you think about it a languaeg like C gives you stuff so that you can still do stuff and make mistakes so in ark you would still be able to write memory secure code and it will still let you make mistakes because that is not a priority in the language unless its like rust

**Comment by kiljacken** [comment]
:+1: If it's theoretically feasable

**Comment by felixangell** [comment]
I suppose this is kind of approved then? We'll wait and see...
