### ISSUE TITLE
Operator overloading

### ISSUE THREAD

**Issue by kiljacken** [ark-lang/rfcs#9]
I believe that ark should support operator overloading. Coming from gamedev perspective it would be very useful for implementing and using vector/matrix/quaternion math cleanly. It would also be useful in the scenarious of various bigint implementations.

The way i propose handling operator overloading, would be to make binops on non-primitive types act as syntactic sugar for a function call ala `a._opname(b)`. So having a two structs, `a` and `b`, of a custom 3d-vector type, `a + b` would expand into `a._add(b)`.

This is ofcourse just a rough sketch of the idea, and more though would have to be given with regards to whether/how to support unary operators, and whether to allow overloading things like array/tuple indexing syntax.

**Comment by MovingtoMars** [comment]
:-1: I'm against it.

----

Read http://yosefk.com/c++fqa/operator.html

----

One of the main reasons is to do with memory management. Say I overload the `+` function to concatenate strings.
```
println(a + b);
```
I've just created a memory leak, because I don't keep I reference to the allocation. This is different to what users expect, which is that `+` never allocates a new heap variable. This is how it works with all the builtin types.

----

Another reason is symmetry. Say you have `type1` and `type2`, which you can use `+` on together. You need to provide matching implimentations of `+` for each type, and make sure they are the same.

The problem gets much worse when you have `type3`, and overload `+` so you can `+` `type3` with another type. Only, this time, that other type is a trait. You have to provide symmetrical overloads for all types that implement that trait, or leave `+` to be order-dependent, creating confusion. On top of this, what if someone importing your library defines their own type, and makes it implement your trait?

----

Overall, is `matrix1.mul(matrix2)` so much worse than `matrix1 * matrix2`?

Although, if we do include it, it should be restricted to a small subset of the available operators (maybe only `+ - * / %`). God forbid we allow overloading `==` and `!=`.

**Comment by kiljacken** [comment]
> Overall, is matrix1.mul(matrix2) so much worse than matrix1 * matrix2?

In my opinion, yes. It scales with complexity

Consider doing 3d graphics or raytracing and having to calculate a reflection.
Supporting overloading (or the option of full language support for vectors, matrices etc) this would be doable like:
`R = 2 * dot(V, N) * N - V`

Compared to the follwing without:
`R= N.scale(2 * dot(V, N)).sub(V)`
Which I don't find nearly as readable

I believe that if we do not allow operator overloading, we instead should consider have language support for vectors / matrices, which would be a lot more work.

**Comment by felixangell** [comment]
Perhaps we can only allow a few operators to be overloaded, and they are overloaded by implementing a specific trait like `Add`. For instance:

```
type Vector2 struct {
    x: f64,
    y: f64
};

impl Add for Vector2 {
    func add(self, other: Vector2): Vector2 {
         return Vector2{x: self.x + other.x, y: self.y + other.y }
    }
}

func main(): int {
     a := Vector2{x: 0, y: 1};
     b := Vector2{x: 1, y: 2};
     c := a + b;
}
```

**Comment by kiljacken** [comment]
That would indeed be a more idiomatic way to do the syntactic part

**Comment by kiljacken** [comment]
> memory management

I really don't like not doing something _just_ because it can be misused. Any function could allocate memory without the user knowing, but we wouldn't disallow functions because of that.

> symmetry

The symmetry problem could be solved by **not** being C++. Having **proper** syntactic support would allow us to do something like:
```
// scale vector
operator Mul for Vector3, f32 { ... }

// hadamard product
operator Mul for Vector3, Vector3 { ... }

// cross product, for gods sake don't bind to * in production
[non-associative]
operator Mul for Vector3, Vector3 { ... } 
```

> Only, this time, that other type is a trait

Implementing an operator for a trait will only have access to the functions exposed by that trait. Thus the implementation wouldn't need changing.

**Comment by SamTebbs33** [comment]
@kiljacken An alternative to your overload syntax could be something like the following:

```
func *(vec: Vector3, operand: f32): Vector3 {
    // multiplication code here
}
func *(vec: Vector3, vec2: Vector3): Vector3 {
    // multiplication code here
}
```

This would be consistent with the current function declaration syntax and may make operator overloading more simple to implement into the compiler because it uses an already present system (function declarations).

**Comment by MovingtoMars** [comment]
With a lot of these operator overloading proposals, we introduce function overloading as well, which I definitely don't like.

@raoulvdberge @vnev @zhiayang?

**Comment by kiljacken** [comment]
@SamTebbs33 I don't quite fancy reusing function syntax for operator overloading, as a separate syntax would allow for an implementation where semantic checks are better/simpler and also avoid polluting the namespace additionally

**Comment by felixangell** [comment]
@MovingtoMars I think you could probably use traits for function overloading if we don't support it anyway

**Comment by raoulvdberge** [comment]
:-1: operator overloading
:-1: function overloading

**Comment by felixangell** [comment]
@raoulvdberge your life :-1:

**Comment by kiljacken** [comment]
Okay. So what I take from this conversation is the main two votes against operator overloading is:
* Lack of guaranteed memory-safety
* Symmetry issues

The first point is, IMO, not really a great argument against. In a C-like language, with a C-like memory model we could never guarantee memory-safety. People could **always** hide allocations somewhere. And if we were to move to an ownership based model (as per #10) this problem would be eliminated completely.

The second point can be easily solved by an implementation better than C++. By either only allowing `type, type => type` overloads via a trait, a lack of symmetry problems would be guaranteed in all instances. Or if proper syntax for specifying `type a, type b => type c` overloads, that are either order dependent (requiring two functions) or order independent (requiring one function), symmetry could be easily handled aswell.

**Comment by MovingtoMars** [comment]
@kiljacken Another reason is that it hides complexity.

**Comment by kiljacken** [comment]
> it hides complexity

But so does using our function call syntax instead of manually pushing arguments to the stack and jumping to the address of the code. Isn't the whole point of programming languages to provide abstractions and allow for the hiding of complexity? I really don't buy this argument.

> few reasons where overloading could be useful

So Vectors, Matrices, Complex numbers, BigInts, BigRationals, BigFloats, Finite Field Arithmetic (for cryptography among other applications), is not enough to warrant the implementation of a useful abstraction, just because **there is the possibility** it might be confusing when misused?

**Comment by vnev** [comment]
:+1:  for operator overloading.

I feel like operator overloading is a good feature to have. Finally, its up to the user to decide whether he wants to use operator overloading to simplify an expression, or not use any operator overloading if he wants to guarantee safety.

**Comment by felixangell** [comment]
Yeah I like this, and I now like ownership too (which gives us memory safety).
